 
 ## App Config custom properties
##app.config.web_service_url_ser=http://localhost:8080/gelis_online_service_live/rest/
#app.config.web_service_url_ser=http://10.4.1.47:1001/
app.config.web_service_url_ser=http://localhost:1515/
#app.config.web_service_url_ser=http://localhost:29090/
app.config.web_service_url_ser_api_key=7059772e-edd5-4bec-b7af-bfdd75af7385
app.config.web_service_url_dlrev_server=https://igf.dlrev.org/webservice/api/

app.config.site_plan_verification=http://localhost:9095/verify_approved_plan?v=

app.config.doc_mgt_api=http://localhost:1031/
app.config.doc_mgt_api_key=7059772e-edd5-4bec-b7af-bfdd75af7385

app.config.doc_mgt_api_v1=http://localhost:1035/
app.config.doc_mgt_api_v1_key=7059772e-edd5-4bec-b7af-bfdd75af7385

app.config.geoserver_url=http://10.4.1.47:2020/geoserver/
app.config.geoserver_workspace_name=csau_geospatial
app.config.geoserver_user=postgres
app.config.geoserver_password=win


# application.properties
spring.mail.host=mail.lc.gov.gh
spring.mail.port=587
spring.mail.username=lc\\hr.test
spring.mail.password=Password.0@2023
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


# Domain authentication properties
spring.mail.properties.mail.smtp.domain=lc
spring.mail.properties.mail.smtp.submitter=hr.test

# SSL/TLS configuration to handle certificate issues
spring.mail.properties.mail.smtp.ssl.trust=*
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

# From address configuration
spring.mail.from.address=hr.test@lc.gov.gh
spring.mail.from.name=Land Commission

app.config.app_folder_path=/Users/edemmawut/Documents/Projects/ELIS/documents/jasper_report_files/


