#app.config.web_service_url_ser=http://10.4.0.74:1002/
#app.config.web_service_url_ser=http://10.4.1.47:1001/
app.config.web_service_url_ser=http://10.4.1.53:1001/
app.config.web_service_url_ser_api_key=fb469d7ef430b0baf0cab6c436e70375
app.config.web_service_url_dlrev_server=https://igf.dlrev.org/webservice/api/

app.config.site_plan_verification=http://10.4.1.53:9095/verify_approved_plan?v=

app.config.doc_mgt_api=http://10.4.1.53:1031/
app.config.doc_mgt_api_key=7059772e-edd5-4bec-b7af-bfdd75af7385

app.config.doc_mgt_api_v1=http://10.4.1.53:1035/
app.config.doc_mgt_api_v1_key=7059772e-edd5-4bec-b7af-bfdd75af7385

app.config.geoserver_url=http://10.4.1.53:2020/geoserver/
app.config.geoserver_workspace_name=csau_geospatial
app.config.geoserver_user=postgres
app.config.geoserver_password=win

# application.properties
spring.mail.host=mail.lc.gov.gh
spring.mail.port=587
spring.mail.username=lc\\hr.test
spring.mail.password=Password.0@2023
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Domain authentication properties
spring.mail.properties.mail.smtp.domain=lc
spring.mail.properties.mail.smtp.submitter=hr.test

# SSL/TLS configuration to handle certificate issues
spring.mail.properties.mail.smtp.ssl.trust=*
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

# From address configuration
spring.mail.from.address=hr.test@lc.gov.gh
spring.mail.from.name=Land Commission

app.config.oblique_file_location=/elisdata/elis/documents/jasper_report_files/
app.config.soft_file_location=/elisdata/elis/documents/jasper_report_files/
app.config.jasper_report_file_location=/elisdata/elis/documents/jasper_report_files/
app.config.pic_file_location=/elisdata/elis/documents/jasper_report_files/
app.config.apkpath=/Users/johnassiamah/Desktop/EPMAv3_22_03_223.apk

app.config.get_public_docs_upload_location=/elisdata/elis/documents/web_docs/
app.config.case_upload_location=/elisdata/elis/documents/case_docs/
app.config.public_docs_upload_location=/elisdata/elis/documents/web_docs/
app.config.softfile_location=/elisdata/elis/softfiles/
app.config.sample_sign_location=/elisdata/elis/softfiles/

app.config.batching_files_location=/elisdata/elis/softfiles/
app.config.publicaton_files_location=/elisdata/elis/documents/publications/
app.config.tempfile_location=/elisdata/elis/documents/temp_upload/
app.config.lrd_jacket_raw_path=/elisdata/elis/documents/lrd_maps/

app.config.legal_batch_list_location=/elisdata/elis/legal/batch_list/
app.config.legal_request_document=/elisdata/elis/legal/request_documents/
app.config.legal_document_location=/elisdata/elis/legal/document_location/
app.config.legal_provide_document=/elisdata/elis/legal/provide_documents/

app.config.cica_reply_document=/elisdata/elis/cica/reply_document/
app.config.cica_created_ticket=/elisdata/elis/cica/created_ticket/
app.config.cica_request_form=/elisdata/elis/cica/request_form/

app.config.lc_temp_folder=/elisdata/elis/lc_temp_folder/
app.config.lc_deleted_case=/elisdata/elis/lc_deleted_case/
app.config.egcr_url=https://cagdmdaapi.paqtechnologies.com/v1/receipts/
app.config.egcr_apikey=nbNe++11+wVPnZmPz+BTSkkxd0hCQsIURKp7cHnpcnw=

    

 ## File upload custom properties
file.upload.oblique_file_location=/elisdata/elis/documents/jasper_report_files/
file.upload.soft_file_location=/elisdata/elis/documents/jasper_report_files/
file.upload.jasper_report_file_location=/elisdata/elis/documents/jasper_report_files/
file.upload.pic_file_location=/elisdata/elis/documents/jasper_report_files/
file.upload.tempfile_location=/elisdata/elis/documents/jasper_report_files/
file.upload.apkpath=/Users/johnassiamah/Desktop/EPMAv3_22_03_223.apk

