spring.application.name=ticket-mgt-app

server.port=7050
spring.profiles.active=dev

# JSP Configuration
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

spring.mvc.throw-exception-if-no-handler-found=true
# spring.web.resources.add-mappings=false

# App Config (Fallbacks)
app.config.web_service_url_ser=http://localhost:1515/
app.config.web_service_url_ser_api_key=7059772e-edd5-4bec-b7af-bfdd75af7385
